# -*- coding: utf-8 -*-
"""Case Study – Machine Learning Using Python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15eMevBWClsQqFctlyfOpbPr0yCJlqABI

1. Using sklearn import the wine dataset
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix

data=pd.read_csv('wine.csv')
data.head()

"""2. Split the data into train and test set"""

x=data.iloc[:,:-1]
x

y=data.iloc[:,-1]
y

x_train,x_test,y_train,y_test=train_test_split(x,y)

"""3. Train the model"""

from sklearn.linear_model import LinearRegression

reg_model=LinearRegression()

reg_model.fit(x_train,y_train)

"""4. Make Predictions"""

y_pred=reg_model.predict(x_test)
y_pred

y_test

"""5. Check the performance of the model using r2_score"""

from sklearn.metrics import r2_score

r2_score(y_test,y_pred)