# -*- coding: utf-8 -*-
"""Hands-On: 6 Data Cleaning.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yAPxWgVCFr2UK9GTbhunTJzF1IwiiioP
"""

#Import the required packages and read data from time_seriest.csv in a dataframe
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

data=pd.read_csv('time_series.csv')
data.head()

#Plot a line graph and take a look at Google’s historical data about its stock price
plt.plot(data['Date'],data['GOOG'])
plt.show()

#Read data from national parks and take a look at first 5 rows.
data1=pd.read_csv('national_parks.csv')
data1.head()

#Plot a histogram based on the ‘GrandCanyon’ column.
plt.hist(data1['GrandCanyon'])
plt.show()

#Read data from ‘types_movies.csv’and take a look at first 5 rows.
data3=pd.read_csv('types_movies.csv')
data3.head()

#Plot a pie chart based on percentage of movies and set labels to be sector column.
plt.pie(data3['Percentage'],labels=data3['Sector'])
plt.show()

#Create and visualize a correlation matrix on time_series data using heatmaps
data=pd.read_csv('time_series.csv')
matrix=data.corr()

sns.heatmap(matrix,annot=True)

