# -*- coding: utf-8 -*-
"""Hands-On: 3 Merge Join and Concat.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Kh4k5TtVqEZ633LTBV8U8ubmBv0BvuoA
"""

#Import the required packages and create two data frames.
import pandas as pd

user=pd.DataFrame({
    'id':[1,2,3,4],
    'name':['a','b','c','d']
})

qualification=pd.DataFrame({
    'user_id':[1,2,3,4],
    'qualification':['e','f','g','h']
})

#Merge the two dataframes.
pd.merge(user,qualification,left_on='id',right_on='user_id')

#Create two data frames.

df1=pd.DataFrame({
    'id':[1,2,3,4],
    'name':['a','b','c','d']
}).set_index('id')

df2=pd.DataFrame({
    'id':[1,2,3,4],
    'qualification':['a','b','c','d']
}).set_index('id')

#Join two dataframes.
df1.join(df2)

#Create 3 data frames.
df1=pd.DataFrame({
    'id':[0,1,2],
    'name':['a','b','c']
}).set_index('id')

df2=pd.DataFrame({
    'id':[3,4,5],
    'name':['d','e','f']
}).set_index('id')

df3=pd.DataFrame({
    'id':[6,7,8],
    'name':['g','h','i']
}).set_index('id')

#Concatenate 3 data frames by them as a list in pd.concat.
pd.concat([df1,df2,df3])

