# -*- coding: utf-8 -*-
"""Hands-On: 1:Data Processing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OeechFCodPc-C1pvOlhjSNgyExy7Nke8
"""

#Import the required packages and create a list.
import numpy as np
import pandas as pd

num_list=[1,2,3,4,5]

#Print the type of the variable.
type(num_list)

#Create and reshape a numpy array.
arr=np.array([1,2,3,4,5,6])
arr

arr=arr.reshape(2,3)
arr

#Create a numpy array filled with zeroes and a numpy array with values from 1 to 9 and reshape it.
np.zeros((1,3))

np.arange(1,10).reshape(3,3)

#Create a Data Frame using a 1d list and a 2d list
pd.DataFrame([1,2,3,4])

pd.DataFrame([[1,2,3],['a','b','c']])

#Create a Data Frame using a dictionary.
pd.DataFrame({'id':[1,2,3],'name':['a','b','c']}).set_index('id')