# -*- coding: utf-8 -*-
"""Hands-on: 7 Creating and testing model..ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iMHizDa2FcTyRu1pv9VsbA2XdYCzn5t4
"""

#Import the required packages and read data from iris.csv in a dataframe.

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix
import seaborn as sns

data=pd.read_csv('iris.csv')
data.head()

#Analyze the shape of data.
data.shape

"""Separate data into X and Y variables and split them into training and testing set with
70/30 ratio.
"""

X=data.iloc[:,:-1]
X

Y=data.iloc[:,-1]
Y

x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=.3)

#Instantiate and train a logistic regression model.

clf=LogisticRegression()

clf.fit(x_train,y_train)

"""Make predictions, check the confusion matrix and count incorrect classifications and
check its accuracy score.
"""

y_pred=clf.predict(x_test)

confusion_matrix(y_test,y_pred)

accuracy_score(y_pred,y_test)

